---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kinecccp/kineluma-app/
    - /bin/rm -rf $DEPLOYPATH/public
    - /bin/mkdir -p $DEPLOYPATH/public $DEPLOYPATH/tmp
    - /bin/cp -R deploy-dist/. $DEPLOYPATH/public/
    - /bin/cp server.js $DEPLOYPATH/server.js
    - /usr/bin/touch $DEPLOYPATH/tmp/restart.txt
